### ISSUE TITLE
Screenshot of button in README?

### ISSUE THREAD

**Issue by huyz** [fehnomenal/intellij-direnv#1]
Can't find the button "next to the Synchronize action".  What's the "Synchronize action"?

Can you put a screenshot in this repo's README and/or in the Plugin homepage?

Thanks

**Comment by huyz** [comment]
Oh I think I found it: it's in the toolbar next to the icon for `Reload All From Disk`.

Can you update the description to more precisely describe as above?

**Comment by fehnomenal** [comment]
Thank you, I added a screenshot and described the location of the button more clearly.

I did this mostly for myself and didn't expect others to use this :sweat_smile:
