### ISSUE TITLE
Update support to 212.* version

### ISSUE THREAD

**Issue by saskenuba** [fehnomenal/intellij-direnv#16]
Hey! Clion 2021.2 just got released.
Would you please update it to support the new version?

Thanks for the awesome plugin.

**Comment by m7mdyahia2** [comment]
I built from source the latest change and it worked

**Comment by fehnomenal** [comment]
Yeah, I thought it would be a simple change but did not yet find the time to debug the error the GH action...

**Comment by m7mdyahia2** [comment]
> Yeah, I thought it would be a simple change but did not yet find the time to debug the error the GH action...

just re-run GH

**Comment by fehnomenal** [comment]
Fixed with v0.2.2. You can either download the zip file from releases or wait for the update to be published.
