### ISSUE TITLE
IntelliJ 2020.3 support

### ISSUE THREAD

**Issue by n-my** [fehnomenal/intellij-direnv#4]
First of all thank you for developing this plugin.

IntelliJ 2020.3 [has been released](https://blog.jetbrains.com/idea/2020/12/intellij-idea-2020-3/). Currently only 2019.3 to 2020.2.4 versions are supported. Do you plan to update this? I can help testing if needed.

Thanks,

**Comment by fehnomenal** [comment]
Hey, thanks for using the plugin. Of course, I will keep it usable in the latest versions. In fact the necessary changes (which is only the version range) are already done but not yet released. 
At first, I wanted to figure out how to read the changed environment variables immediately without needing to open the settings dialog. But I will release an update shortly to keep dogfooding.

**Comment by fehnomenal** [comment]
If you cannot wait, grab the latest version here: https://github.com/fehnomenal/intellij-direnv/releases/tag/v0.1.2

**Comment by n-my** [comment]
Sounds great, thanks!
