### ISSUE TITLE
Support GoLand 2024.2 EAP (242.*)

### ISSUE THREAD

**Issue by pan93412** [fehnomenal/intellij-direnv#55]
According to [the version information](https://plugins.jetbrains.com/plugin/15285-direnv-integration/versions/stable/474937), it does not support the 2024.2 EAP.

Hopefully it can get fixed!

> Not specifying until-build means it will include all future builds. This includes future, yet unreleased versions and possibly new IDEs, which might impact compatibility later. [src](https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#build-number-validity)

**Comment by fehnomenal** [comment]
Fixed by #56
