### ISSUE TITLE
I don't see the button to reload on mac. Is there anyway to reload manually?

### ISSUE THREAD

**Issue by siyopao** [fehnomenal/intellij-direnv#6]
As the title says. Thank you!

**Comment by siyopao** [comment]
Oh, I had hidden the toolbar. I found it now 👍  But I would prefer to hide the toolbar so it would still be nice if there was a way to run it manually or with a command.

**Comment by fehnomenal** [comment]
I think you can execute the action via Double-Shift (search anything) "direnv" but I thought about adding a menu item.

Do you think the tools menu would be a good fit?

**Comment by siyopao** [comment]
Weird. I hadn't noticed that I could just execute it using the double-shift. Cool. That's all I need. Thanks! But, yes, I think the tools menu would also be a good place to have it.
