### ISSUE TITLE
Allow autoimport on project start of .envrc

### ISSUE THREAD

**Issue by andre-krueger** [fehnomenal/intellij-direnv#9]
It should be possible to configure the plugin to automatically source the .envrc on project startup.

**Comment by akrger** [comment]
Maybe this could be of help to implement that feature:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009819660-How-to-trigger-an-action-on-Application-startup-or-restart

**Comment by fehnomenal** [comment]
I will have a look into this and include a settings screen.
